import { Question } from './types.ts';

export const QUESTIONS: Question[] = [
  {
    id: 1,
    tenseType: 'past',
    tenseLabelEs: 'Pasado (Pretérito Indefinido)',
    tenseLabelHy: 'Անցյալ (Pretérito Indefinido)',
    situationEs: 'Ayer llegaste tarde a clase. El profesor pregunta: «¿Por qué llegaste tarde?»',
    situationHy: 'Երեկ ուշացել ես դասից։ Ուսուցիչը հարցնում է․ «Ինչո՞ւ ուշացար»։',
    options: {
      A: { es: 'Llegaré tarde mañana.', hy: 'Վաղը կուշանամ։' },
      B: { es: 'Perdí el autobús.', hy: 'Բաց թողեցի ավտոբուսը։' },
      C: { es: 'Pierdo el autobús todos los días.', hy: 'Ամեն օր բաց եմ թողնում ավտոբուսը։' },
      D: { es: 'Voy a perder el autobús.', hy: 'Պատրաստվում եմ բաց թողնել ավտոբուսը։' },
    },
    correct: 'B',
    explanationEs: '«Ayer» requiere Pretérito Indefinido («Perdí»). Es una acción completada y puntual en el pasado.',
    explanationHy: '«Ayer» (երեկ) բառը պահանջում է անցյալ կատարյալ («Perdí»)՝ կոնկրետ ավարտված գործողություն։',
  },
  {
    id: 2,
    tenseType: 'past',
    tenseLabelEs: 'Pasado (Pretérito Indefinido)',
    tenseLabelHy: 'Անցյալ (Pretérito Indefinido)',
    situationEs: 'Tu amigo pregunta: «¿Qué hiciste el fin de semana?»',
    situationHy: 'Ընկերդ հարցնում է․ «Ի՞նչ արեցիր հանգստյան օրերին»։',
    options: {
      A: { es: 'Fui al cine con mi familia.', hy: 'Ընտանիքիս հետ գնացի կինոթատրոն։' },
      B: { es: 'Iré al cine mañana.', hy: 'Վաղը կգնամ կինոթատրոն։' },
      C: { es: 'Voy al cine cada sábado.', hy: 'Ամեն շաբաթ գնում եմ կինոթատրոն։' },
      D: { es: 'Estoy en el cine.', hy: 'Կինոթատրոնում եմ։' },
    },
    correct: 'A',
    explanationEs: '«Hiciste» es Pretérito Indefinido, por lo que la respuesta correcta es «Fui» (fui al cine).',
    explanationHy: '«Hiciste» (արեցիր) հարցին պատասխանում ենք անցյալով՝ «Fui» (գնացի)։',
  },
  {
    id: 3,
    tenseType: 'past',
    tenseLabelEs: 'Pasado (Pretérito Perfecto)',
    tenseLabelHy: 'Անցյալ (Pretérito Perfecto)',
    situationEs: 'Te preguntan: «¿Has desayunado hoy?»',
    situationHy: 'Քեզ հարցնում են․ «Այսօր նախաճաշե՞լ ես»։',
    options: {
      A: { es: 'Desayunaba a las ocho.', hy: 'Նախաճաշում էի ժամը ութին։' },
      B: { es: 'Desayunaré después.', hy: 'Հետո կնախաճաշեմ։' },
      C: { es: 'Sí, he desayunado hace una hora.', hy: 'Այո՛, մեկ ժամ առաջ նախաճաշել եմ։' },
      D: { es: 'Desayuno todos los días.', hy: 'Ամեն օր նախաճաշում եմ։' },
    },
    correct: 'C',
    explanationEs: '«Hoy» indica un periodo temporal no terminado, requiriendo Pretérito Perfecto («he desayunado»).',
    explanationHy: '«Hoy» (այսօր) ժամանակային ցուցիչը պահանջում է Pretérito Perfecto («he desayunado»)։',
  },
  {
    id: 4,
    tenseType: 'past',
    tenseLabelEs: 'Pasado (Pretérito Imperfecto)',
    tenseLabelHy: 'Անցյալ (Pretérito Imperfecto)',
    situationEs: 'Cuando eras pequeño, ¿qué hacías después de la escuela?',
    situationHy: 'Երբ փոքր էիր, ի՞նչ էիր անում դպրոցից հետո։',
    options: {
      A: { es: 'Jugaba con mis amigos.', hy: 'Խաղում էի ընկերներիս հետ։' },
      B: { es: 'Jugué mañana.', hy: 'Վաղը խաղացի։' },
      C: { es: 'Jugaré ayer.', hy: 'Երեկ կխաղամ։' },
      D: { es: 'He jugado mañana.', hy: 'Վաղը խաղացել եմ։' },
    },
    correct: 'A',
    explanationEs: 'Para acciones habituales en la infancia se utiliza el Pretérito Imperfecto («Jugaba»).',
    explanationHy: 'Մանկության կրկնվող սովորությունների համար գործածվում է Pretérito Imperfecto («Jugaba»)։',
  },
  {
    id: 5,
    tenseType: 'past',
    tenseLabelEs: 'Pasado (Pretérito Indefinido)',
    tenseLabelHy: 'Անցյալ (Pretérito Indefinido)',
    situationEs: 'Ayer llovió mucho. ¿Qué hiciste?',
    situationHy: 'Երեկ շատ անձրև եկավ։ Ի՞նչ արեցիր։',
    options: {
      A: { es: 'Saldré al parque.', hy: 'Կգնամ այգի։' },
      B: { es: 'Me quedé en casa.', hy: 'Մնացի տանը։' },
      C: { es: 'Estoy en casa mañana.', hy: 'Վաղը տանն եմ։' },
      D: { es: 'Salgo ayer.', hy: 'Երեկ դուրս եմ գալիս։' },
    },
    correct: 'B',
    explanationEs: '«Ayer» sitúa la acción en el pasado puntual («Me quedé en casa»).',
    explanationHy: '«Ayer» (երեկ) ցույց է տալիս անցյալ կատարյալ գործողություն («Me quedé»)։',
  },
  {
    id: 6,
    tenseType: 'past',
    tenseLabelEs: 'Pasado (Pretérito Perfecto)',
    tenseLabelHy: 'Անցյալ (Pretérito Perfecto)',
    situationEs: 'Tu madre pregunta: «¿Ya has hecho los deberes?»',
    situationHy: 'Մայրդ հարցնում է․ «Արդեն արե՞լ ես տնային աշխատանքը»։',
    options: {
      A: { es: 'Haré los deberes ayer.', hy: 'Երեկ կանեմ տնային աշխատանքը։' },
      B: { es: 'Hacía los deberes mañana.', hy: 'Վաղը անում էի տնայինը։' },
      C: { es: 'Sí, ya los he hecho.', hy: 'Այո՛, արդեն արել եմ։' },
      D: { es: 'Hago los deberes después.', hy: 'Հետո անում եմ։' },
    },
    correct: 'C',
    explanationEs: '«¿Ya has hecho...?» se responde en Pretérito Perfecto («ya los he hecho»).',
    explanationHy: '«Ya has hecho...?» հարցին համապատասխանում է «Sí, ya los he hecho»։',
  },
  {
    id: 7,
    tenseType: 'past',
    tenseLabelEs: 'Pasado (Pretérito Indefinido)',
    tenseLabelHy: 'Անցյալ (Pretérito Indefinido)',
    situationEs: 'Tu amigo pregunta: «¿Cómo fue el partido de ayer?»',
    situationHy: 'Ընկերդ հարցնում է․ «Ինչպե՞ս անցավ երեկվա խաղը»։',
    options: {
      A: { es: 'Será muy emocionante.', hy: 'Շատ հետաքրքիր կլինի։' },
      B: { es: 'Fue muy emocionante y ganamos.', hy: 'Շատ հետաքրքիր էր, և մենք հաղթեցինք։' },
      C: { es: 'Es mañana.', hy: 'Վաղն է։' },
      D: { es: 'Hemos ganado mañana.', hy: 'Վաղը հաղթել ենք։' },
    },
    correct: 'B',
    explanationEs: '«El partido de ayer» exige Indefinido: «Fue muy emocionante y ganamos».',
    explanationHy: 'Երեկվա խաղի համար գործածվում է անցյալ կատարյալը՝ «Fue» և «ganamos»։',
  },
  {
    id: 8,
    tenseType: 'past',
    tenseLabelEs: 'Pasado Continuo / Imperfecto',
    tenseLabelHy: 'Անցյալ շարունակական (Estaba + gerundio)',
    situationEs: '¿Qué hacías cuando te llamé anoche?',
    situationHy: 'Ի՞նչ էիր անում, երբ երեկ երեկոյան զանգեցի քեզ։',
    options: {
      A: { es: 'Estaba cenando.', hy: 'Ընթրում էի։' },
      B: { es: 'Cenaré.', hy: 'Կընթրեմ։' },
      C: { es: 'He cenado mañana.', hy: 'Վաղը ընթրել եմ։' },
      D: { es: 'Ceno ayer.', hy: 'Երեկ ընթրում եմ։' },
    },
    correct: 'A',
    explanationEs: 'Acción en progreso interrumpida en el pasado: «Estaba cenando».',
    explanationHy: 'Անցյալում ընթացքի մեջ գտնվող գործողություն՝ «Estaba cenando» (ընթրում էի)։',
  },
  {
    id: 9,
    tenseType: 'past',
    tenseLabelEs: 'Pasado (Pretérito Indefinido)',
    tenseLabelHy: 'Անցյալ (Pretérito Indefinido)',
    situationEs: 'Te preguntan: «¿Dónde estuviste ayer por la tarde?»',
    situationHy: 'Քեզ հարցնում են․ «Որտե՞ղ էիր երեկ կեսօրից հետո»։',
    options: {
      A: { es: 'Estaré en casa.', hy: 'Տանը կլինեմ։' },
      B: { es: 'Estoy en casa mañana.', hy: 'Վաղը տանն եմ։' },
      C: { es: 'Estuve en la biblioteca.', hy: 'Գրադարանում էի։' },
      D: { es: 'He estado mañana.', hy: 'Վաղը եղել եմ։' },
    },
    correct: 'C',
    explanationEs: '«Ayer por la tarde» requiere Indefinido del verbo estar: «Estuve».',
    explanationHy: '«Ayer por la tarde» ժամանակային հղումը պահանջում է «Estuve» (էի/եղա)։',
  },
  {
    id: 10,
    tenseType: 'past',
    tenseLabelEs: 'Pasado (Pretérito Perfecto)',
    tenseLabelHy: 'Անցյալ (Pretérito Perfecto)',
    situationEs: '¿Has visto esta película?',
    situationHy: 'Դիտե՞լ ես այս ֆիլմը։',
    options: {
      A: { es: 'Sí, la he visto dos veces.', hy: 'Այո՛, երկու անգամ դիտել եմ։' },
      B: { es: 'La veré ayer.', hy: 'Երեկ կդիտեմ։' },
      C: { es: 'La veía mañana.', hy: 'Վաղը դիտում էի։' },
      D: { es: 'La veo la semana pasada.', hy: 'Անցած շաբաթ դիտում եմ։' },
    },
    correct: 'A',
    explanationEs: 'Experiencia vital en Pretérito Perfecto: «Sí, la he visto dos veces».',
    explanationHy: 'Կյանքի փորձի հարցին պատասխան՝ «Sí, la he visto dos veces» (դիտել եմ)։',
  },
  {
    id: 11,
    tenseType: 'past',
    tenseLabelEs: 'Pasado (Pretérito Indefinido)',
    tenseLabelHy: 'Անցյալ (Pretérito Indefinido)',
    situationEs: '¿Qué comiste ayer en el restaurante?',
    situationHy: 'Ի՞նչ կերար երեկ ռեստորանում։',
    options: {
      A: { es: 'Comeré pescado.', hy: 'Ձուկ կուտեմ։' },
      B: { es: 'Comí pasta y una ensalada.', hy: 'Մակարոն և աղցան կերա։' },
      C: { es: 'Como ayer.', hy: 'Երեկ ուտում եմ։' },
      D: { es: 'He comido mañana.', hy: 'Վաղը կերել եմ։' },
    },
    correct: 'B',
    explanationEs: '«Ayer» exige Indefinido del verbo comer en primera persona: «Comí».',
    explanationHy: '«Ayer» (երեկ) ցուցիչովcomer բայի 1-ին դեմքը՝ «Comí» (կերա)։',
  },
  {
    id: 12,
    tenseType: 'past',
    tenseLabelEs: 'Pasado (Pretérito Imperfecto)',
    tenseLabelHy: 'Անցյալ (Pretérito Imperfecto)',
    situationEs: 'Cuando vivías en España, ¿ibas mucho a la playa?',
    situationHy: 'Երբ ապրում էիր Իսպանիայում, հաճա՞խ էիր գնում լողափ։',
    options: {
      A: { es: 'Iré todos los domingos.', hy: 'Ամեն կիրակի կգնամ։' },
      B: { es: 'Sí, iba casi todos los fines de semana.', hy: 'Այո՛, գրեթե ամեն հանգստյան օր գնում էի։' },
      C: { es: 'Fui mañana.', hy: 'Վաղը գնացի։' },
      D: { es: 'Voy ayer.', hy: 'Երեկ գնում եմ։' },
    },
    correct: 'B',
    explanationEs: 'Acción repetida y habitual en el pasado: «iba casi todos los fines de semana».',
    explanationHy: 'Անցյալում կրկնվող սովորություն՝ «iba casi todos los fines de semana» (գնում էի)։',
  },
  {
    id: 13,
    tenseType: 'past',
    tenseLabelEs: 'Pasado (Pretérito Indefinido)',
    tenseLabelHy: 'Անցյալ (Pretérito Indefinido)',
    situationEs: 'Tu amiga pregunta: «¿Qué pasó con tu móvil?»',
    situationHy: 'Ընկերուհիդ հարցնում է․ «Ի՞նչ պատահեց հեռախոսիդ»։',
    options: {
      A: { es: 'Lo perderé.', hy: 'Կկորցնեմ այն։' },
      B: { es: 'Se me cayó al suelo.', hy: 'Այն ընկավ ձեռքիցս գետնին։' },
      C: { es: 'Se cae mañana.', hy: 'Վաղը ընկնում է։' },
      D: { es: 'Lo pierdo ayer.', hy: 'Երեկ կորցնում եմ։' },
    },
    correct: 'B',
    explanationEs: 'Suceso accidental puntual en el pasado: «Se me cayó al suelo».',
    explanationHy: 'Անցյալում տեղի ունեցած անակնկալ դեպք՝ «Se me cayó al suelo» (ընկավ գետնին)։',
  },
  {
    id: 14,
    tenseType: 'past',
    tenseLabelEs: 'Pasado (Pretérito Perfecto)',
    tenseLabelHy: 'Անցյալ (Pretérito Perfecto)',
    situationEs: '¿Has hablado hoy con Ana?',
    situationHy: 'Այսօր խոսե՞լ ես Աննայի հետ։',
    options: {
      A: { es: 'Hablaré ayer.', hy: 'Երեկ կխոսեմ։' },
      B: { es: 'Sí, he hablado con ella esta mañana.', hy: 'Այո՛, այսօր առավոտյան խոսել եմ նրա հետ։' },
      C: { es: 'Hablaba mañana.', hy: 'Վաղը խոսում էի։' },
      D: { es: 'Hablo la semana pasada.', hy: 'Անցած շաբաթ խոսում եմ։' },
    },
    correct: 'B',
    explanationEs: '«Esta mañana» pertenece al día presente, por lo que requiere «he hablado».',
    explanationHy: '«Esta mañana» (այսօր առավոտյան) պահանջում է Pretérito Perfecto՝ «he hablado»։',
  },
  {
    id: 15,
    tenseType: 'past',
    tenseLabelEs: 'Pasado (Pretérito Imperfecto)',
    tenseLabelHy: 'Անցյալ (Pretérito Imperfecto)',
    situationEs: 'De niño, ¿qué deporte practicabas?',
    situationHy: 'Փոքր ժամանակ ի՞նչ սպորտով էիր զբաղվում։',
    options: {
      A: { es: 'Practicaré fútbol.', hy: 'Ֆուտբոլով կզբաղվեմ։' },
      B: { es: 'Practicaba fútbol y tenis.', hy: 'Ֆուտբոլ և թենիս էի խաղում։' },
      C: { es: 'He practicado mañana.', hy: 'Վաղը զբաղվել եմ։' },
      D: { es: 'Practico ayer.', hy: 'Երեկ զբաղվում եմ։' },
    },
    correct: 'B',
    explanationEs: '«De niño» indica hábitos del pasado, expresados en Imperfecto («Practicaba»).',
    explanationHy: '«De niño» (մանկության տարիներին) պահանջում է Imperfecto՝ «Practicaba»։',
  },
  {
    id: 16,
    tenseType: 'past',
    tenseLabelEs: 'Pasado (Pretérito Imperfecto - Causa)',
    tenseLabelHy: 'Անցյալ (Pretérito Imperfecto)',
    situationEs: 'El profesor pregunta: «¿Por qué no viniste ayer?»',
    situationHy: 'Ուսուցիչը հարցնում է․ «Ինչո՞ւ երեկ չեկար»։',
    options: {
      A: { es: 'Porque estaba enfermo.', hy: 'Որովհետև հիվանդ էի։' },
      B: { es: 'Porque estaré enfermo.', hy: 'Որովհետև հիվանդ կլինեմ։' },
      C: { es: 'Porque estoy enfermo mañana.', hy: 'Որովհետև վաղը հիվանդ եմ։' },
      D: { es: 'Porque he estado mañana.', hy: 'Որովհետև վաղը եղել եմ։' },
    },
    correct: 'A',
    explanationEs: 'Describe el estado físico en el pasado («estaba enfermo»).',
    explanationHy: 'Անցյալում առողջական վիճակի նկարագրություն՝ «estaba enfermo» (հիվանդ էի)։',
  },
  {
    id: 17,
    tenseType: 'past',
    tenseLabelEs: 'Pasado (Pretérito Indefinido)',
    tenseLabelHy: 'Անցյալ (Pretérito Indefinido)',
    situationEs: '¿Qué compraste en el supermercado?',
    situationHy: 'Ի՞նչ գնեցիր սուպերմարկետից։',
    options: {
      A: { es: 'Comprarás fruta.', hy: 'Մրգեր կգնես։' },
      B: { es: 'Compré leche, pan y fruta.', hy: 'Կաթ, հաց և միրգ գնեցի։' },
      C: { es: 'Compro ayer.', hy: 'Երեկ գնում եմ։' },
      D: { es: 'Compraba mañana.', hy: 'Վաղը գնում էի։' },
    },
    correct: 'B',
    explanationEs: 'Respuesta directa a «compraste» en Pretérito Indefinido: «Compré».',
    explanationHy: '«Compraste» (գնեցիր) հարցի պատասխանը առաջին դեմքով՝ «Compré» (գնեցի)։',
  },
  {
    id: 18,
    tenseType: 'past',
    tenseLabelEs: 'Pasado (Pretérito Imperfecto)',
    tenseLabelHy: 'Անցյալ (Pretérito Imperfecto)',
    situationEs: '¿Qué estabas haciendo cuando empezó a llover?',
    situationHy: 'Ի՞նչ էիր անում, երբ սկսեց անձրև գալ։',
    options: {
      A: { es: 'Caminaba por el parque.', hy: 'Զբոսնում էի այգում։' },
      B: { es: 'Caminaré mañana.', hy: 'Վաղը կզբոսնեմ։' },
      C: { es: 'He caminado mañana.', hy: 'Վաղը զբոսնել եմ։' },
      D: { es: 'Camino ayer.', hy: 'Երեկ զբոսնում եմ։' },
    },
    correct: 'A',
    explanationEs: 'Acción que estaba en desarrollo en el pasado: «Caminaba por el parque».',
    explanationHy: 'Անցյալում ընթացիկ գործողություն՝ «Caminaba por el parque» (զբոսնում էի այգում)։',
  },
  {
    id: 19,
    tenseType: 'past',
    tenseLabelEs: 'Pasado (Pretérito Perfecto)',
    tenseLabelHy: 'Անցյալ (Pretérito Perfecto)',
    situationEs: '¿Has terminado el libro?',
    situationHy: 'Ավարտե՞լ ես գիրքը։',
    options: {
      A: { es: 'Sí, lo he terminado hoy.', hy: 'Այո՛, այսօր ավարտել եմ։' },
      B: { es: 'Lo terminaré ayer.', hy: 'Երեկ կավարտեմ։' },
      C: { es: 'Lo terminaba mañana.', hy: 'Վաղը ավարտում էի։' },
      D: { es: 'Lo termino la semana pasada.', hy: 'Անցած շաբաթ ավարտում եմ։' },
    },
    correct: 'A',
    explanationEs: '«Hoy» y la acción reciente concuerdan con «he terminado».',
    explanationHy: '«Hoy» (այսօր) բառը համապատասխանում է «he terminado» ձևին։',
  },
  {
    id: 20,
    tenseType: 'past',
    tenseLabelEs: 'Pasado (Pretérito Imperfecto)',
    tenseLabelHy: 'Անցյալ (Pretérito Imperfecto)',
    situationEs: '¿Cómo era tu escuela cuando eras pequeño?',
    situationHy: 'Ինչպիսի՞ն էր քո դպրոցը, երբ փոքր էիր։',
    options: {
      A: { es: 'Será grande.', hy: 'Մեծ կլինի։' },
      B: { es: 'Era pequeña pero muy bonita.', hy: 'Փոքր էր, բայց շատ գեղեցիկ։' },
      C: { es: 'Es mañana.', hy: 'Վաղն է։' },
      D: { es: 'Fue todos los días.', hy: 'Ամեն օր եղավ։' },
    },
    correct: 'B',
    explanationEs: 'Para describir características pasadas se emplea «Era» (Pretérito Imperfecto de ser).',
    explanationHy: 'Անցյալում նկարագրության համար օգտագործվում է «Era» (էր)։',
  },
  {
    id: 21,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Simple',
    tenseLabelHy: 'Ապառնի (Futuro Simple)',
    situationEs: 'Tu amigo pregunta: «¿Qué harás mañana?»',
    situationHy: 'Ընկերդ հարցնում է․ «Ի՞նչ ես անելու վաղը»։',
    options: {
      A: { es: 'Fui al trabajo.', hy: 'Գնացի աշխատանքի։' },
      B: { es: 'Trabajaba en casa.', hy: 'Աշխատում էի տանը։' },
      C: { es: 'Iré al trabajo y después descansaré.', hy: 'Կգնամ աշխատանքի, հետո կհանգստանամ։' },
      D: { es: 'He trabajado ayer.', hy: 'Երեկ աշխատել եմ։' },
    },
    correct: 'C',
    explanationEs: '«Mañana» exige futuro: «Iré al trabajo y después descansaré».',
    explanationHy: '«Mañana» (վաղը) պահանջում է ապառնի ժամանակ՝ «Iré» և «descansaré»։',
  },
  {
    id: 22,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Simple',
    tenseLabelHy: 'Ապառնի (Futuro Simple)',
    situationEs: '¿Dónde pasarás tus próximas vacaciones?',
    situationHy: 'Որտե՞ղ կանցկացնես հաջորդ արձակուրդդ։',
    options: {
      A: { es: 'Estuve en Italia.', hy: 'Իտալիայում էի։' },
      B: { es: 'Las pasaré en España.', hy: 'Կանցկացնեմ Իսպանիայում։' },
      C: { es: 'Las pasaba en casa.', hy: 'Տանն էի անցկացնում։' },
      D: { es: 'He estado ayer.', hy: 'Երեկ եղել եմ։' },
    },
    correct: 'B',
    explanationEs: '«Próximas vacaciones» es tiempo futuro: «Las pasaré en España».',
    explanationHy: '«Próximas vacaciones» (հաջորդ արձակուրդ) նշանակում է ապառնի՝ «Las pasaré»։',
  },
  {
    id: 23,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Próximo (Ir a + infinitivo)',
    tenseLabelHy: 'Մոտալուտ ապառնի (Ir a + infinitivo)',
    situationEs: 'Mañana tienes un examen. ¿Qué vas a hacer esta noche?',
    situationHy: 'Վաղը քննություն ունես։ Ի՞նչ ես անելու այսօր երեկոյան։',
    options: {
      A: { es: 'Estudié ayer.', hy: 'Երեկ սովորեցի։' },
      B: { es: 'Voy a estudiar y después voy a dormir temprano.', hy: 'Սովորելու եմ, հետո շուտ եմ քնելու։' },
      C: { es: 'Estudiaba cuando era pequeño.', hy: 'Սովորում էի, երբ փոքր էի։' },
      D: { es: 'He estudiado mañana.', hy: 'Վաղը սովորել եմ։' },
    },
    correct: 'B',
    explanationEs: '«¿Qué vas a hacer?» se responde con la misma perífrasis: «Voy a estudiar...».',
    explanationHy: '«¿Qué vas a hacer?» (ի՞նչ ես պատրաստվում անել) պատասխանն է «Voy a estudiar...»։',
  },
  {
    id: 24,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Simple',
    tenseLabelHy: 'Ապառնի (Futuro Simple)',
    situationEs: '¿Qué comerás esta noche?',
    situationHy: 'Ի՞նչ ես ուտելու այսօր երեկոյան։',
    options: {
      A: { es: 'Comí pasta.', hy: 'Մակարոն կերա։' },
      B: { es: 'Comía sopa.', hy: 'Ապուր էի ուտում։' },
      C: { es: 'Prepararé pollo con verduras.', hy: 'Հավ և բանջարեղեն կպատրաստեմ։' },
      D: { es: 'He comido ayer.', hy: 'Երեկ կերել եմ։' },
    },
    correct: 'C',
    explanationEs: '«Esta noche» en pregunta de futuro («comerás») requiere «Prepararé».',
    explanationHy: 'Ապառնի հարցին («comerás») համապատասխանում է «Prepararé» (կպատրաստեմ)։',
  },
  {
    id: 25,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Simple',
    tenseLabelHy: 'Ապառնի (Futuro Simple)',
    situationEs: 'Tu amiga te invita al cine mañana. ¿Qué respondes?',
    situationHy: 'Ընկերուհիդ հրավիրում է քեզ վաղը կինոթատրոն։ Ի՞նչ ես պատասխանում։',
    options: {
      A: { es: 'Fui contigo ayer.', hy: 'Երեկ քեզ հետ գնացի։' },
      B: { es: 'Sí, iré contigo.', hy: 'Այո՛, քեզ հետ կգնամ։' },
      C: { es: 'Iba contigo cuando era pequeño.', hy: 'Փոքր ժամանակ քեզ հետ էի գնում։' },
      D: { es: 'He ido mañana.', hy: 'Վաղը գնացել եմ։' },
    },
    correct: 'B',
    explanationEs: 'Respuesta afirmativa para un plan de mañana: «Sí, iré contigo».',
    explanationHy: 'Վաղվա պլանի համար դրական պատասխան՝ «Sí, iré contigo» (կգնամ քեզ հետ)։',
  },
  {
    id: 26,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Simple (Condicional Real)',
    tenseLabelHy: 'Ապառնի (Պայմանական իրական)',
    situationEs: '¿Qué harás si mañana hace buen tiempo?',
    situationHy: 'Ի՞նչ կանես, եթե վաղը լավ եղանակ լինի։',
    options: {
      A: { es: 'Fui al parque.', hy: 'Գնացի այգի։' },
      B: { es: 'Iré a caminar por el parque.', hy: 'Կգնամ զբոսնելու այգում։' },
      C: { es: 'Iba al parque.', hy: 'Գնում էի այգի։' },
      D: { es: 'He ido ayer.', hy: 'Երեկ գնացել եմ։' },
    },
    correct: 'B',
    explanationEs: 'Estructura condicional tipo 1: «Si + presente, futuro» («Iré a caminar...»).',
    explanationHy: 'Իրական պայմանական կառույց (Si + Presente, Futuro)՝ «Iré a caminar por el parque»։',
  },
  {
    id: 27,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Simple',
    tenseLabelHy: 'Ապառնի (Futuro Simple)',
    situationEs: '¿A qué hora te levantarás mañana?',
    situationHy: 'Վաղը ժամը քանիսի՞ն կարթնանաս։',
    options: {
      A: { es: 'Me levanté a las siete.', hy: 'Ժամը յոթին արթնացա։' },
      B: { es: 'Me levantaba temprano.', hy: 'Շուտ էի արթնանում։' },
      C: { es: 'Me levantaré a las siete.', hy: 'Ժամը յոթին կարթնանամ։' },
      D: { es: 'Me he levantado ayer.', hy: 'Երեկ արթնացել եմ։' },
    },
    correct: 'C',
    explanationEs: '«Mañana» requiere futuro en primera persona: «Me levantaré a las siete».',
    explanationHy: '«Mañana» (վաղը) պահանջում է ապառնի 1-ին դեմք՝ «Me levantaré» (կարթնանամ)։',
  },
  {
    id: 28,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Próximo (Ir a + infinitivo)',
    tenseLabelHy: 'Մոտալուտ ապառնի (Ir a + infinitivo)',
    situationEs: '¿Qué vas a comprar este fin de semana?',
    situationHy: 'Ի՞նչ ես գնելու այս հանգստյան օրերին։',
    options: {
      A: { es: 'Compré zapatos.', hy: 'Կոշիկ գնեցի։' },
      B: { es: 'Voy a comprar una chaqueta nueva.', hy: 'Նոր բաճկոն եմ գնելու։' },
      C: { es: 'Compraba fruta.', hy: 'Մրգեր էի գնում։' },
      D: { es: 'He comprado ayer.', hy: 'Երեկ գնել եմ։' },
    },
    correct: 'B',
    explanationEs: 'La pregunta usa «vas a comprar», por lo que responde «Voy a comprar...».',
    explanationHy: 'Հարցը «vas a comprar» ձևով է, ուստի պատասխանն է «Voy a comprar...»։',
  },
  {
    id: 29,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Simple',
    tenseLabelHy: 'Ապառնի (Futuro Simple)',
    situationEs: 'Mañana es el cumpleaños de tu amigo. ¿Qué harás?',
    situationHy: 'Վաղը ընկերոջդ ծննդյան օրն է։ Ի՞նչ կանես։',
    options: {
      A: { es: 'Le di un regalo ayer.', hy: 'Երեկ նրան նվեր տվեցի։' },
      B: { es: 'Le compraré un regalo.', hy: 'Նրան նվեր կգնեմ։' },
      C: { es: 'Le daba regalos de niño.', hy: 'Փոքր ժամանակ նրան նվերներ էի տալիս։' },
      D: { es: 'Le he comprado ayer.', hy: 'Երեկ գնել եմ։' },
    },
    correct: 'B',
    explanationEs: 'Plan para mañana: «Le compraré un regalo».',
    explanationHy: 'Վաղվա նախատեսվող գործողություն՝ «Le compraré un regalo» (նվեր կգնեմ)։',
  },
  {
    id: 30,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Simple',
    tenseLabelHy: 'Ապառնի (Futuro Simple)',
    situationEs: '¿Qué profesión tendrás en el futuro?',
    situationHy: 'Ապագայում ի՞նչ մասնագիտություն կունենաս։',
    options: {
      A: { es: 'Fui profesor.', hy: 'Ուսուցիչ եղա։' },
      B: { es: 'Era profesor mañana.', hy: 'Վաղը ուսուցիչ էի։' },
      C: { es: 'Seré profesor.', hy: 'Ուսուցիչ կլինեմ։' },
      D: { es: 'He sido mañana.', hy: 'Վաղը եղել եմ։' },
    },
    correct: 'C',
    explanationEs: '«En el futuro» requiere el Futuro Simple de ser: «Seré profesor».',
    explanationHy: '«En el futuro» (ապագայում) պահանջում է «Seré» (կլինեմ)։',
  },
  {
    id: 31,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Simple',
    tenseLabelHy: 'Ապառնի (Futuro Simple)',
    situationEs: '¿A qué país viajarás el próximo año?',
    situationHy: 'Հաջորդ տարի ո՞ր երկիր կճամփորդես։',
    options: {
      A: { es: 'Viajé a Francia ayer.', hy: 'Երեկ Ֆրանսիա ճամփորդեցի։' },
      B: { es: 'Viajaba a menudo.', hy: 'Հաճախ էի ճամփորդում։' },
      C: { es: 'Viajaré a Italia.', hy: 'Կճամփորդեմ Իտալիա։' },
      D: { es: 'He viajado mañana.', hy: 'Վաղը ճամփորդել եմ։' },
    },
    correct: 'C',
    explanationEs: '«El próximo año» sitúa la acción en futuro: «Viajaré a Italia».',
    explanationHy: '«El próximo año» (հաջորդ տարի) ցույց է տալիս ապառնի ժամանակ՝ «Viajaré»։',
  },
  {
    id: 32,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Simple',
    tenseLabelHy: 'Ապառնի (Futuro Simple)',
    situationEs: '¿Dónde vivirás cuando seas mayor?',
    situationHy: 'Որտե՞ղ կապրես, երբ մեծանաս։',
    options: {
      A: { es: 'Viví en el campo.', hy: 'Գյուղում ապրեցի։' },
      B: { es: 'Viviré cerca del mar.', hy: 'Կապրեմ ծովի մոտ։' },
      C: { es: 'Vivía en una ciudad pequeña.', hy: 'Փոքր քաղաքում էի ապրում։' },
      D: { es: 'Vivo ayer.', hy: 'Երեկ ապրում եմ։' },
    },
    correct: 'B',
    explanationEs: 'La cláusula temporal con subjuntivo («cuando seas mayor») rige Futuro Simple: «Viviré».',
    explanationHy: '«Cuando seas mayor» (երբ մեծանաս) կառույցը պահանջում է ապառնի՝ «Viviré» (կապրեմ)։',
  },
  {
    id: 33,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Simple',
    tenseLabelHy: 'Ապառնի (Futuro Simple)',
    situationEs: 'Tu jefe pregunta: «¿Cuándo terminarás el informe?»',
    situationHy: 'Ղեկավարդ հարցնում է․ «Ե՞րբ կավարտես հաշվետվությունը»։',
    options: {
      A: { es: 'Lo terminé el año pasado.', hy: 'Անցյալ տարի ավարտեցի։' },
      B: { es: 'Lo terminaré antes de las cinco.', hy: 'Կավարտեմ մինչև ժամը հինգը։' },
      C: { es: 'Lo terminaba ayer.', hy: 'Երեկ էի ավարտում։' },
      D: { es: 'Lo he terminado mañana.', hy: 'Վաղը ավարտել եմ։' },
    },
    correct: 'B',
    explanationEs: 'Compromiso de entrega en el futuro: «Lo terminaré antes de las cinco».',
    explanationHy: 'Ապագայում ավարտելու խոստում՝ «Lo terminaré» (կավարտեմ)։',
  },
  {
    id: 34,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Próximo (Ir a + infinitivo)',
    tenseLabelHy: 'Մոտալուտ ապառնի (Ir a + infinitivo)',
    situationEs: '¿Qué vas a cocinar para la cena de hoy?',
    situationHy: 'Ի՞նչ ես պատրաստելու այսօրվա ընթրիքի համար։',
    options: {
      A: { es: 'Cociné una tortilla.', hy: 'Տորտիլյա պատրաստեցի։' },
      B: { es: 'Voy a cocinar sopa de verduras.', hy: 'Բանջարեղենային ապուր եմ պատրաստելու։' },
      C: { es: 'Cocinaba con mi abuela.', hy: 'Տատիկիս հետ էի պատրաստում։' },
      D: { es: 'Cocino ayer por la tarde.', hy: 'Երեկ կեսօրին եմ պատրաստում։' },
    },
    correct: 'B',
    explanationEs: 'Intención inmediata expresada con ir a + infinitivo: «Voy a cocinar...».',
    explanationHy: 'Մոտալուտ նպատակադրություն՝ «Voy a cocinar sopa de verduras»։',
  },
  {
    id: 35,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Simple',
    tenseLabelHy: 'Ապառնի (Futuro Simple)',
    situationEs: 'Si tienes tiempo libre el domingo, ¿qué harás?',
    situationHy: 'Եթե կիրակի ազատ ժամանակ ունենաս, ի՞նչ կանես։',
    options: {
      A: { es: 'Leí tres libros.', hy: 'Երեք գիրք կարդացի։' },
      B: { es: 'Leeré una novela interesante.', hy: 'Հետաքրքիր վեպ կկարդամ։' },
      C: { es: 'Leía todos los días.', hy: 'Ամեն օր կարդում էի։' },
      D: { es: 'He leído mañana.', hy: 'Վաղը կարդացել եմ։' },
    },
    correct: 'B',
    explanationEs: 'Consecuencia futura en oración condicional real: «Leeré una novela».',
    explanationHy: 'Իրական պայմանական նախադասության արդյունք ապառնիում՝ «Leeré» (կկարդամ)։',
  },
  {
    id: 36,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Simple',
    tenseLabelHy: 'Ապառնի (Futuro Simple)',
    situationEs: '¿A quién llamarás cuando llegues a casa?',
    situationHy: 'Ո՞ւմ կզանգես, երբ հասնես տուն։',
    options: {
      A: { es: 'Llamé a mis padres ayer.', hy: 'Երեկ ծնողներիս զանգեցի։' },
      B: { es: 'Llamaré a mi madre.', hy: 'Կզանգեմ մայրիկիս։' },
      C: { es: 'Llamaba todos los viernes.', hy: 'Ամեն ուրբաթ զանգում էի։' },
      D: { es: 'Llamo ayer a las diez.', hy: 'Երեկ ժամը տասին եմ զանգում։' },
    },
    correct: 'B',
    explanationEs: '«Llamarás» en la pregunta pide respuesta en futuro: «Llamaré a mi madre».',
    explanationHy: 'Հարցի ապառնի ձևին («Llamarás») համապատասխանում է «Llamaré» (կզանգեմ)։',
  },
  {
    id: 37,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Próximo (Ir a + infinitivo)',
    tenseLabelHy: 'Մոտալուտ ապառնի (Ir a + infinitivo)',
    situationEs: '¿Qué idioma vas a aprender después del español?',
    situationHy: 'Իսպաներենից հետո ի՞նչ լեզու ես սովորելու։',
    options: {
      A: { es: 'Aprendí alemán en la escuela.', hy: 'Դպրոցում գերմաներեն սովորեցի։' },
      B: { es: 'Voy a aprender italiano.', hy: 'Իտալերեն եմ սովորելու։' },
      C: { es: 'Aprendía inglés de niño.', hy: 'Մանկության տարիներին անգլերեն էի սովորում։' },
      D: { es: 'He aprendido mañana.', hy: 'Վաղը սովորել եմ։' },
    },
    correct: 'B',
    explanationEs: '«¿Qué idioma vas a aprender...?» -> «Voy a aprender italiano».',
    explanationHy: 'Հարցը նախատեսվող գործողության մասին է՝ «Voy a aprender italiano»։',
  },
  {
    id: 38,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Simple',
    tenseLabelHy: 'Ապառնի (Futuro Simple)',
    situationEs: 'Tu hermano pregunta: «¿Vendrás a mi fiesta el sábado?»',
    situationHy: 'Եղբայրդ հարցնում է․ «Կգա՞ս իմ խնջույքին շաբաթ օրը»։',
    options: {
      A: { es: 'Sí, vendré sin falta.', hy: 'Այո՛, անպայման կգամ։' },
      B: { es: 'Vine anoche tarde.', hy: 'Երեկ երեկոյան ուշ եկա։' },
      C: { es: 'Venía siempre a tus fiestas.', hy: 'Միշտ գալիս էի քո խնջույքներին։' },
      D: { es: 'He venido mañana temprano.', hy: 'Վաղը շուտ եմ եկել։' },
    },
    correct: 'A',
    explanationEs: 'Promesa o confirmación para el sábado venidero: «Sí, vendré sin falta».',
    explanationHy: 'Առաջիկա շաբաթ օրվա հաստատում՝ «Sí, vendré sin falta» (անպայման կգամ)։',
  },
  {
    id: 39,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Simple',
    tenseLabelHy: 'Ապառնի (Futuro Simple)',
    situationEs: '¿Cuánto dinero ahorrarás este mes?',
    situationHy: 'Որքա՞ն գումար կխնայես այս ամիս։',
    options: {
      A: { es: 'Ahorré mucho el año pasado.', hy: 'Անցյալ տարի շատ խնայեցի։' },
      B: { es: 'Ahorraba cuando era estudiante.', hy: 'Ուսանող եղած ժամանակ էի խնայում։' },
      C: { es: 'Ahorraré doscientos euros.', hy: 'Երկու հարյուր եվրո կխնայեմ։' },
      D: { es: 'Ahorro ayer.', hy: 'Երեկ խնայում եմ։' },
    },
    correct: 'C',
    explanationEs: 'Acción proyectada a lo largo del mes: «Ahorraré doscientos euros».',
    explanationHy: 'Ապառնի գործողություն՝ «Ahorraré doscientos euros» (կխնայեմ)։',
  },
  {
    id: 40,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Simple',
    tenseLabelHy: 'Ապառնի (Futuro Simple)',
    situationEs: '¿A qué concierto irás el próximo mes?',
    situationHy: 'Ո՞ր համերգին կգնաս հաջորդ ամիս։',
    options: {
      A: { es: 'Fui al concierto de rock.', hy: 'Ռոք համերգին գնացի։' },
      B: { es: 'Iba a conciertos cada mes.', hy: 'Ամեն ամիս համերգների էի գնում։' },
      C: { es: 'Iré al concierto de música clásica.', hy: 'Կգնամ դասական երաժշտության համերգի։' },
      D: { es: 'Voy ayer con mis amigos.', hy: 'Երեկ գնում եմ ընկերներիս հետ։' },
    },
    correct: 'C',
    explanationEs: '«El próximo mes» ubica la acción en el futuro: «Iré al concierto...».',
    explanationHy: '«El próximo mes» (հաջորդ ամիս) նշանակում է «Iré» (կգնամ)։',
  },
  {
    id: 41,
    tenseType: 'past',
    tenseLabelEs: 'Pasado (Pretérito Indefinido)',
    tenseLabelHy: 'Անցյալ (Pretérito Indefinido)',
    situationEs: 'Ayer perdiste las llaves de casa. ¿Cómo entraste?',
    situationHy: 'Երեկ կորցրիր տան բանալիները։ Ինչպե՞ս ներս մտար։',
    options: {
      A: { es: 'Entraré por el balcón.', hy: 'Պատշգամբից ներս կմտնեմ։' },
      B: { es: 'Llamé a mi hermano y me abrió la puerta.', hy: 'Զանգեցի եղբորս, և նա բացեց դուռը։' },
      C: { es: 'Entro mañana.', hy: 'Վաղը ներս եմ մտնում։' },
      D: { es: 'He entrado la próxima semana.', hy: 'Հաջորդ շաբաթ եմ ներս մտել։' },
    },
    correct: 'B',
    explanationEs: 'Acciones concluidas en el pasado puntual («Llamé» y «abrió»).',
    explanationHy: 'Երեկվա կոնկրետ ավարտված քայլեր՝ «Llamé» (զանգեցի) և «abrió» (բացեց)։',
  },
  {
    id: 42,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Simple',
    tenseLabelHy: 'Ապառնի (Futuro Simple)',
    situationEs: 'El camarero pregunta: «¿Qué van a tomar de postre?»',
    situationHy: 'Մատուցողը հարցնում է․ «Ի՞նչ եք վերցնելու որպես աղանդեր»։',
    options: {
      A: { es: 'Tomé pastel de chocolate.', hy: 'Շոկոլադե տորթ վերցրի։' },
      B: { es: 'Tomaba helado de niño.', hy: 'Փոքր ժամանակ պաղպաղակ էի վերցնում։' },
      C: { es: 'Tomaremos café y helado.', hy: 'Սուրճ և պաղպաղակ կվերցնենք։' },
      D: { es: 'He tomado ayer.', hy: 'Երեկ եմ վերցրել։' },
    },
    correct: 'C',
    explanationEs: 'Decisión para los próximos minutos expresada en futuro de cortesía/elección: «Tomaremos...».',
    explanationHy: 'Պատվերի ընտրություն՝ «Tomaremos café y helado» (կվերցնենք)։',
  },
  {
    id: 43,
    tenseType: 'past',
    tenseLabelEs: 'Pasado (Pretérito Indefinido)',
    tenseLabelHy: 'Անցյալ (Pretérito Indefinido)',
    situationEs: '¿Dónde estuviste el verano pasado?',
    situationHy: 'Որտե՞ղ էիր անցյալ ամառ։',
    options: {
      A: { es: 'Estaré en Grecia.', hy: 'Հունաստանում կլինեմ։' },
      B: { es: 'Estuve en la montaña con amigos.', hy: 'Ընկերներիս հետ սարերում էի։' },
      C: { es: 'Estoy en la montaña mañana.', hy: 'Վաղը սարերում եմ։' },
      D: { es: 'Voy a estar la semana pasada.', hy: 'Անցած շաբաթ պատրաստվում եմ լինել։' },
    },
    correct: 'B',
    explanationEs: '«El verano pasado» es un tiempo cerrado en el pasado, requiere «Estuve».',
    explanationHy: '«El verano pasado» (անցյալ ամառ) պահանջում է անցյալ կատարյալ՝ «Estuve» (էի/եղա)։',
  },
  {
    id: 44,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Simple',
    tenseLabelHy: 'Ապառնի (Futuro Simple)',
    situationEs: 'Tu amiga te pregunta: «¿Cuándo me devolverás el libro?»',
    situationHy: 'Ընկերուհիդ հարցնում է․ «Ե՞րբ ինձ կվերադարձնես գիրքը»։',
    options: {
      A: { es: 'Te lo devolví la semana pasada.', hy: 'Անցած շաբաթ քեզ վերադարձրի այն։' },
      B: { es: 'Te lo devolveré este viernes.', hy: 'Այս ուրբաթ կվերադարձնեմ այն քեզ։' },
      C: { es: 'Te lo devolvía de niño.', hy: 'Մանկության տարիներին էի քեզ վերադարձնում։' },
      D: { es: 'Te lo devuelvo ayer.', hy: 'Երեկ քեզ վերադարձնում եմ։' },
    },
    correct: 'B',
    explanationEs: 'Promesa hacia una fecha futura próxima: «Te lo devolveré este viernes».',
    explanationHy: 'Ապառնի ժամանակով խոստում՝ «Te lo devolveré este viernes» (այս ուրբաթ կվերադարձնեմ)։',
  },
  {
    id: 45,
    tenseType: 'past',
    tenseLabelEs: 'Pasado Continuo (Estaba + gerundio)',
    tenseLabelHy: 'Անցյալ շարունակական (Estaba + gerundio)',
    situationEs: '¿Qué hacías cuando sonó la alarma de incendios?',
    situationHy: 'Ի՞նչ էիր անում, երբ հնչեց հրդեհի ազդանշանը։',
    options: {
      A: { es: 'Estaba trabajando en la oficina.', hy: 'Գրասենյակում էի աշխատում։' },
      B: { es: 'Trabajaré en la oficina mañana.', hy: 'Վաղը գրասենյակում կաշխատեմ։' },
      C: { es: 'He trabajado la próxima semana.', hy: 'Հաջորդ շաբաթ աշխատել եմ։' },
      D: { es: 'Trabajo ayer por la mañana.', hy: 'Երեկ առավոտյան աշխատում եմ։' },
    },
    correct: 'A',
    explanationEs: 'Acción en progreso en el instante de una interrupción: «Estaba trabajando».',
    explanationHy: 'Ընդհատված ընթացիկ գործողություն անցյալում՝ «Estaba trabajando» (աշխատում էի)։',
  },
  {
    id: 46,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Simple',
    tenseLabelHy: 'Ապառնի (Futuro Simple)',
    situationEs: '¿Qué harás si apruebas todos los exámenes?',
    situationHy: 'Ի՞նչ կանես, եթե հանձնես բոլոր քննությունները։',
    options: {
      A: { es: 'Lo celebré con una fiesta.', hy: 'Խնջույքով նշեցի։' },
      B: { es: 'Lo celebraba todos los años.', hy: 'Ամեն տարի էի նշում։' },
      C: { es: 'Haré una gran fiesta con mis amigos.', hy: 'Մեծ խնջույք կկազմակերպեմ ընկերներիս հետ։' },
      D: { es: 'Hago una fiesta ayer.', hy: 'Երեկ խնջույք եմ անում։' },
    },
    correct: 'C',
    explanationEs: 'Consecuencia de una condición futura: «Haré una gran fiesta...».',
    explanationHy: 'Ապագա իրադարձության պլան՝ «Haré una gran fiesta con mis amigos» (խնջույք կանեմ)։',
  },
  {
    id: 47,
    tenseType: 'past',
    tenseLabelEs: 'Pasado (Pretérito Indefinido)',
    tenseLabelHy: 'Անցյալ (Pretérito Indefinido)',
    situationEs: 'Tu abuelo pregunta: «¿Quién pintó este cuadro tan bonito?»',
    situationHy: 'Պապիկդ հարցնում է․ «Ո՞վ նկարեց այս գեղեցիկ նկարը»։',
    options: {
      A: { es: 'Lo pintará mi hermana mañana.', hy: 'Վաղը քույրս կնկարի այն։' },
      B: { es: 'Lo pintó mi madre hace muchos años.', hy: 'Մայրս է նկարել շատ տարիներ առաջ։' },
      C: { es: 'Lo pinta la próxima semana.', hy: 'Հաջորդ շաբաթ նկարում է։' },
      D: { es: 'Lo pintaba mañana por la tarde.', hy: 'Վաղը կեսօրին էր նկարում։' },
    },
    correct: 'B',
    explanationEs: '«Hace muchos años» indica un evento histórico completado: «Lo pintó mi madre».',
    explanationHy: '«Hace muchos años» (տարիներ առաջ) պահանջում է անցյալ կատարյալ՝ «Lo pintó» (նկարեց)։',
  },
  {
    id: 48,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Simple',
    tenseLabelHy: 'Ապառնի (Futuro Simple)',
    situationEs: '¿A qué hora te acostarás hoy?',
    situationHy: 'Ժամը քանիսի՞ն կքնես այսօր։',
    options: {
      A: { es: 'Me acosté a medianoche.', hy: 'Կեսգիշերին քնեցի։' },
      B: { es: 'Me acostaba temprano de pequeño.', hy: 'Փոքր ժամանակ շուտ էի քնում։' },
      C: { es: 'Me acostaré a las once de la noche.', hy: 'Գիշերը ժամը տասնմեկին կքնեմ։' },
      D: { es: 'Me he acostado ayer.', hy: 'Երեկ եմ քնել։' },
    },
    correct: 'C',
    explanationEs: 'Plan para más tarde esta noche: «Me acostaré a las once de la noche».',
    explanationHy: 'Այս գիշերվա պլան՝ «Me acostaré a las once de la noche» (կպառկեմ քնելու)։',
  },
  {
    id: 49,
    tenseType: 'past',
    tenseLabelEs: 'Pasado (Pretérito Perfecto)',
    tenseLabelHy: 'Անցյալ (Pretérito Perfecto)',
    situationEs: '¿Has visitado alguna vez Madrid?',
    situationHy: 'Երբևէ եղե՞լ ես Մադրիդում։',
    options: {
      A: { es: 'Sí, he estado allí dos veces.', hy: 'Այո՛, երկու անգամ եղել եմ այնտեղ։' },
      B: { es: 'Estaré allí ayer.', hy: 'Երեկ կլինեմ այնտեղ։' },
      C: { es: 'Estaba allí la próxima semana.', hy: 'Հաջորդ շաբաթ այնտեղ էի։' },
      D: { es: 'Estoy allí el año pasado.', hy: 'Անցյալ տարի այնտեղ եմ։' },
    },
    correct: 'A',
    explanationEs: 'Pregunta de experiencia existencial con «alguna vez», respondida con «he estado».',
    explanationHy: '«Alguna vez» (երբևէ) հարցին պատասխան՝ «Sí, he estado allí dos veces» (եղել եմ)։',
  },
  {
    id: 50,
    tenseType: 'future',
    tenseLabelEs: 'Futuro Simple',
    tenseLabelHy: 'Ապառնի (Futuro Simple)',
    situationEs: '¿Qué tiempo hará mañana en la ciudad?',
    situationHy: 'Ինչպիսի՞ եղանակ կլինի վաղը քաղաքում։',
    options: {
      A: { es: 'Hizo mucho frío ayer.', hy: 'Երեկ շատ ցուրտ էր։' },
      B: { es: 'Hacía sol en mi infancia.', hy: 'Մանկությանս տարիներին արևոտ էր։' },
      C: { es: 'Hará sol y una temperatura agradable.', hy: 'Արևոտ և հաճելի ջերմաստիճան կլինի։' },
      D: { es: 'Ha hecho sol mañana.', hy: 'Վաղը արևոտ է եղել։' },
    },
    correct: 'C',
    explanationEs: 'Predicción meteorológica para mañana: «Hará sol y una temperatura agradable».',
    explanationHy: 'Վաղվա եղանակի կանխատեսում՝ «Hará sol...» (արևոտ կլինի)։',
  },
];

// Millionaire Ladder prize values (in Armenian Drams / Դրամ)
export const LADDER_15_PRIZES = [
  { level: 1, amount: '1,000 ֏', raw: 1000, safe: false },
  { level: 2, amount: '2,000 ֏', raw: 2000, safe: false },
  { level: 3, amount: '3,000 ֏', raw: 3000, safe: false },
  { level: 4, amount: '5,000 ֏', raw: 5000, safe: false },
  { level: 5, amount: '10,000 ֏', raw: 10000, safe: true }, // Milestone 1
  { level: 6, amount: '20,000 ֏', raw: 20000, safe: false },
  { level: 7, amount: '40,000 ֏', raw: 40000, safe: false },
  { level: 8, amount: '75,000 ֏', raw: 75000, safe: false },
  { level: 9, amount: '125,000 ֏', raw: 125000, safe: false },
  { level: 10, amount: '250,000 ֏', raw: 250000, safe: true }, // Milestone 2
  { level: 11, amount: '400,000 ֏', raw: 400000, safe: false },
  { level: 12, amount: '600,000 ֏', raw: 600000, safe: false },
  { level: 13, amount: '750,000 ֏', raw: 750000, safe: false },
  { level: 14, amount: '900,000 ֏', raw: 900000, safe: false },
  { level: 15, amount: '1,000,000 ֏', raw: 1000000, safe: true }, // Grand Prize!
];
